language: cpp

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:
  apt:
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - cmake