language: cpp

dist: trusty
sudo: required
group: edge

matrix:
  include:

  - os: linux
      compiler: gcc
      env: COMPILER=g++-4.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: g++-4.9